services:
  frontend:
    build: frontend
    depends_on:
      - backend
    tty: true
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /frontend/
        - action: rebuild
          path: ./frontend/package.json
    environment:
      VITE_BACKEND_ORIGIN: "https://api.filestage.ahmadalasiri.info"
      PORT: 3000
    ports:
      - "3000:3000"

  backend:
    build: backend
    depends_on:
      - database
    tty: true
    develop:
      watch:
        - action: sync+restart
          path: ./backend
          target: /backend/
        - action: rebuild
          path: ./backend/package.json
    ports:
      - "3001:3001"
    environment:
      DOMAIN: "filestage.ahmadalasiri.info"
      PORT: 3001
      FRONTEND_ORIGIN: "https://filestage.ahmadalasiri.info"
      COOKIE_SECRET: "s3cr3t"
      MONGO_URI: "mongodb://root:1234@database:27017"
      SMTP_NAME: "Filestage"
      SMTP_USERNAME: "ahmed.elasiri2@gmail.com"
      SMTP_PASSWORD: "fhbe rkfb esgn ibpy"
      SMTP_HOST: "smtp.gmail.com"
      SMTP_PORT: 465

  database:
    image: mongo:5.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "1234"
