services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.prod
    restart: always
    depends_on:
      - backend
    environment:
      VITE_BACKEND_ORIGIN: "https://api.filestage.ahmadalasiri.info"
      PORT: 3000
    ports:
      - "3000:3000"

  backend:
    build:
      context: backend
      dockerfile: Dockerfile.prod
    restart: always
    depends_on:
      - database
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: "production"
      DOMAIN: "filestage.ahmadalasiri.info"
      PORT: 3001
      FRONTEND_ORIGIN: "https://filestage.ahmadalasiri.info"
      COOKIE_SECRET: "s3cr3t"
      MONGO_URI: "mongodb://root:1234@database:27017"
      SMTP_NAME: "Filestage"
      SMTP_USERNAME: "ahmed.elasiri2@gmail.com"
      SMTP_PASSWORD: "fhbe rkfb esgn ibpy"
      SMTP_HOST: "smtp.gmail.com"
      SMTP_PORT: 465

  database:
    image: mongo:5.0
    restart: always
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "1234"

volumes:
  mongo_data:
